before_script:
  - docker info
  - docker-compose --version

stages:
  - deploy

Deploy Site:
  stage: deploy
  only:
    - master
  script:
    - docker-compose up -d --build --force-recreate
  environment: production
  when: always
