version: '3.1'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SHOPIFY_API_KEY
      - SHOPIFY_API_SECRET_KEY
      - DB_URI
      - DB_NAME
    networks:
      - app-network
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - app-network
    command: ["--bind_ip_all"]
  redis:
    image: redis:alpine


networks:
  app-network:
    driver: bridge

volumes:
  mongodata:
