version: '3.1'

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SHOPIFY_API_KEY
      - SHOPIFY_API_SECRET_KEY
      - DB_URI
      - DB_NAME
